config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :channels do
    resources :messages
    member do
      post :join
      delete :leave
    end
  end
  root "channels#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :messages
  has_many :channel_users, dependent: :destroy
  has_many :users, through: :channel_users

  validates :name, presence: true
end

app/models/channel_user.rb
class ChannelUser < ApplicationRecord
  belongs_to :channel
  belongs_to :user
  after_create :broadcast_members
  after_destroy :remove_broadcast_members

  def broadcast_members
    broadcast_append_to(
      [ channel, "users" ],
      target: "channel-members",
      partial: "users/user",
      locals: { user: user }
    )
  end

  def remove_broadcast_members
    broadcast_remove_to(
      [ channel, "users" ],
      target: "user_#{user.id}"
    )
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :channel
  belongs_to :user
  validates :content, presence: true
  after_create :broadcast_message

  def broadcast_message
    broadcast_append_to(
      [ channel, "messages" ],
      target: "messages",
      partial: "messages/message",
      locals: { message: self }
    )
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages
  has_many :channel_users, dependent: :destroy
  has_many :channels, through: :channel_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_channel, only: %i[ show edit update destroy join leave ]

  # GET /channels or /channels.json
  def index
    @channels = Channel.all
  end

  # GET /channels/1 or /channels/1.json
  def show
    @members = @channel.users
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels or /channels.json
  def create
    @channel = Channel.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: "Channel was successfully created." }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1 or /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: "Channel was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1 or /channels/1.json
  def destroy
    @channel.destroy!

    respond_to do |format|
      format.html { redirect_to channels_path, notice: "Channel was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  # POST /channels/:id/join
  def join
    @channel.channel_users.find_or_create_by(user: current_user)
    respond_to do |format|
      format.html { redirect_to @channel }
      format.json { head :no_content }
    end
  end

  # DELETE /channels/:id/leave
  def leave
    membership = @channel.channel_users.find_by(user: current_user)
    membership&.destroy
    respond_to do |format|
      format.html { redirect_to channels_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def channel_params
      params.expect(channel: [ :name ])
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :set_channel

    def create
        @message = @channel.messages.create(message_params)
        @message.user = current_user
        @message.save

        render json: {}, status: :no_content
    end

    private

    def set_channel
        @channel ||= Channel.find(params[:channel_id])
    end

    def message_params
        params.require(:message).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/channels/_channel.html.erb
<div id="<%= dom_id channel %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Name:</strong>
    <%= channel.name %>
  </div>
</div>

app/views/channels/_form.html.erb
<%= form_with(model: channel, class: "contents") do |form| %>
  <% if channel.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul class="list-disc ml-6">
        <% channel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": channel.errors[:name].none?, "border-red-400 focus:outline-red-600": channel.errors[:name].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<% content_for :title, "Editing channel" %>

<div class="md:w-300 w-300 mx-auto mt-4 mb-2 p-4 bg-gray-800 rounded-lg shadow text-gray-100">
  <%= link_to "<", @channel, class: "text-center sm:mt-0 sm:ml-2 rounded-md px-3.5 py-3.5 bg-gray-800 hover:underline inline-block font-medium text-gray-100" %>

  <h1 class="font-bold text-4xl text-gray-100 inline-block">Edit channel</h1>

  <%= render "form", channel: @channel %>
</div>

app/views/channels/index.html.erb
<% content_for :title, "Channels" %>

<div class="md:w-300 w-300 mt-4 mb-2 p-4 bg-gray-800 rounded-lg shadow mx-auto">
  <div class="flex justify-between items-center mb-4">
    <h1 class="font-bold text-4xl text-white">Channels</h1>
    <%= link_to "New channel", new_channel_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="channels" class="min-w-full mx-auto divide-y divide-gray-200 space-y-5 items-center">
    <% if @channels.any? %>
      <% @channels.each do |channel| %>
        <div class=" pb-5 flex items-center">
          <% if current_user && channel.users.include?(current_user) %>
          <%= link_to "##{channel.name}", channel, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 hover:bg-gray-700 inline-block font-medium text-white mr-8" %>
          <%= link_to "Edit", edit_channel_path(channel), class: "w-full sm:w-auto text-center rounded-md px-1.5 py-1.5 bg-gray-700 hover:bg-gray-600 inline-block font-medium text-white mr-3" %>
          <%= link_to "Delete", channel, method: :delete, class: "w-full sm:w-auto text-center rounded-md px-1.5 py-1.5 text-white bg-red-900 hover:bg-red-700 inline-block font-medium cursor-pointer mr-3", data: { turbo_confirm: "Are you sure?" } %>
          <%= button_to "Leave", leave_channel_path(channel), method: :delete, class: "w-full sm:w-auto text-center rounded-md px-1.5 py-1.5 text-white bg-orange-900 hover:bg-orange-700 inline-block mr-3 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          <% else %>
            <%= link_to "##{channel.name}", nil, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 inline-block font-medium text-white mr-8 cursor-not-allowed" %>
            <%= button_to "Join channel", join_channel_path(channel), method: :post, class: "w-full sm:w-auto text-center rounded-md px-1.5 py-1.5 text-white bg-green-900 hover:bg-green-700 inline-block font-medium cursor-pointer" %>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No channels found.</p>
    <% end %>
  </div>
</div>

app/views/channels/new.html.erb
<% content_for :title, "New channel" %>

<div class="md:w-300 w-300 mx-auto mt-4 mb-2 p-4 bg-gray-800 rounded-lg shadow text-gray-100">
  <%= link_to "<", @channel, class: "text-center sm:mt-0 sm:ml-2 rounded-md px-3.5 py-3.5 bg-gray-800 hover:underline inline-block font-medium text-gray-100" %>

  <h1 class="font-bold text-4xl text-gray-100 inline-block">New channel</h1>

  <%= render "form", channel: @channel %>

</div>

app/views/channels/show.html.erb
<div class="md:w-300 w-300 mt-4 mb-2 p-4 bg-gray-800 rounded-lg shadow mx-auto">
  <div class="flex items-center mb-4 justify-between">
    <div class="flex flex-col sm:flex-row mt-4 mb-2 ">
      <%= link_to "<", channels_path, class: "text-center sm:mt-0 sm:ml-2 rounded-md px-3.5 py-3.5 bg-gray-800 hover:underline inline-block font-medium text-gray-100" %>
      <h1 class="font-bold text-4xl inline-block text-gray-100 mr-8">#<%= @channel.name %></h1>
      <%= link_to "Edit channel", edit_channel_path(@channel), class: "text-center rounded-md px-1.5 py-1.5 bg-gray-800 hover:underline inline-block font-medium text-gray-100" %>
    </div>
    <div id="channel-members" class="mt-4 mb-2 p-4 bg-gray-800 rounded-lg shadow inline-block">
      <h2 class="font-bold text-lg text-gray-100 ml-4 inline-block">Members:</h2>
        <%= turbo_stream_from @channel, "users" %>
        <%= render @channel.users %>
    </div>
  </div>

  <div class="w-full h-155 bg-gray-800 shadow rounded-lg px-5 my-4 mt-4">
    <div id="chat" class="h-155 space-y-4 my-4 overflow-y-auto">
      <div id="messages">
        <%= turbo_stream_from @channel, "messages" %>
        <%= render @channel.messages %>
      </div>
    </div>

    <script>
      new MutationObserver(() => chat.scrollTop = chat.scrollHeight)
        .observe(chat, {childList: true, subtree: true});
      chat.scrollTop = chat.scrollHeight;
    </script>
</div>

  <%= form_with model: [@channel, Message.new], class: "mt-4", data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" } do |f| %>
    <div class="flex gap-4 items-center px-2 py-3 bg-gray-800 rounded-lg">
      <%= f.text_field :content,
          class: "flex-1 min-h-[80px] rounded-lg border-gray-600 bg-gray-700 text-gray-100 shadow-sm focus:border-indigo-400 focus:ring-indigo-400 px-3 py-2 resize-none focus:outline-none suggestions-none",
          placeholder: "Type your message..."
        %>

      <%= f.submit "Send",
        class: "rounded-lg py-3 px-5 bg-blue-700 text-white inline-block font-medium cursor-pointer hover:bg-blue-600"
      %>
    </div>
  <% end %>

<%# field reset after sending a message %>
  <script>
    document.addEventListener('turbo:submit-end', function(e) {
      if (e.detail.success) e.target.reset();
    });
  </script>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Slack Clone" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Slack Clone">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="mx-auto bg-gray-800 min-h-screen">
    <div class="min-h-full">
      <nav class="bg-gray-800 shadow-sm">
        <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div class="flex h-16 justify-between items-center">
            <div class="flex">
              <div class="flex-shrink-0 flex items-center py-2 px-3">
                <%= link_to "Slack Clone", root_path, class: "text-white font-bold text-xl" %>
              </div>
            </div>
            <% if notice.present? %>
              <p class="py-2 px-3 bg-gray-650 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
            <% end %>
            <div class="hidden sm:-my-px sm:ml-6 sm:flex sm:space-x-8 py-2 px-3 items-center">
              <% if current_user %>
                <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-700 text-gray-100 font-medium hover:bg-gray-600 cursor-pointer" %>
              <% else %>
                <%= button_to "Login", new_user_session_path, class: "mt-2 rounded-lg py-3 px-5 bg-gray-700 text-gray-100 font-medium hover:bg-gray-600 cursor-pointer" %>
              <% end %>
            </div>
          </div>
        </div>
      </nav>

    </div>


    <main>
      <div class="">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/messages/_message.html.erb
<div data-controller="channel-messages" class="p-4 my-4 border-b border-gray-700">
  <div class="flex justify-between items-start">
    <div class="font-bold text-gray-100">
      <%= message.user.email.split('@').first %>
    </div>
    <div class="text-sm text-gray-400">
      <%= time_ago_in_words(message.created_at) %> ago
    </div>
  </div>
  <div class="mt-2 text-gray-300">
    <%= message.content %>
  </div>
</div>

app/views/users/_user.html.erb
<div id="<%= dom_id(user) %>" data-controller="channel-members" class="inline-block">
  <div class="">
    <div class="font-bold text-gray-100">
      <%= user.email.split('@').first %>, 
    </div>
  </div>
</div>